<a href="https://colab.research.google.com/github/Yaroslav-Maloshuk/ML/blob/main/%D0%9B%D0%A0_1_%D0%9C%D0%B0%D0%BB%D0%BE%D1%88%D1%83%D0%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі.

In [9]:
import numpy as np
np.__version__

'2.0.2'

In [10]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[2, 5, 4],
       [2, 2, 1],
       [3, 4, 1]])

In [12]:
det = np.linalg.det(matrix)
det

np.float64(9.000000000000002)

In [13]:
product = np.prod(matrix)
product

np.int64(1920)

In [14]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1 * prod_2 * prod_3

np.int64(1920)

In [16]:
np.sum(matrix)

np.int64(24)

In [17]:
np.max(matrix)

np.int64(5)

In [18]:
np.min(matrix)

np.int64(1)

In [19]:
np.mean(matrix)

np.float64(2.6666666666666665)

In [53]:
sqrt_matrix = np.sqrt(matrix)
sqrt_matrix

array([[1.41421356, 2.23606798, 2.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.73205081, 2.        , 1.        ]])

In [54]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
row_sums

array([[11],
       [ 5],
       [ 8]])

In [25]:
matrix.sum(axis=1).reshape(-1, 1)

array([[11],
       [ 5],
       [ 8]])

In [26]:
x = np.matrix([[1, 2], [4, 3]])
x

matrix([[1, 2],
        [4, 3]])

In [27]:
x.sum(axis=1)

matrix([[3],
        [7]])

In [28]:
x.sum(axis=1, dtype='float')

matrix([[3.],
        [7.]])

In [29]:
vector = np.random.randint(0, 10, size=25)
vector

array([3, 4, 7, 6, 8, 1, 5, 6, 6, 0, 0, 7, 8, 2, 8, 0, 8, 5, 0, 5, 8, 4,
       3, 7, 8])

In [30]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([8, 8, 8, 8, 8, 8, 7, 7, 7, 6, 6, 6, 5, 5, 5, 4, 4, 3, 3, 2, 1, 0,
       0, 0, 0])

In [55]:
from scipy import stats

mode = stats.mode(vector)
mode


ModeResult(mode=np.int64(8), count=np.int64(6))

In [56]:
median = np.median(vector)
median

np.float64(5.0)

In [57]:
mean = np.mean(vector)
mean

np.float64(4.76)

In [58]:
max_value = np.max(vector)
max_value

np.int64(8)

In [59]:
min_value = np.min(vector)
min_value

np.int64(0)

In [38]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix1

array([[ 8,  8,  5, 10],
       [ 5,  4,  3,  2],
       [ 5, 10,  1,  1],
       [ 1,  5,  1,  4]])

In [39]:
matrix2 = np.random.randint(1, 11, size=(4, 4))
matrix2

array([[ 1, 10,  3,  7],
       [ 5, 10,  8,  1],
       [ 3,  6,  1,  4],
       [ 3,  4,  6,  5]])

In [41]:
matrix_sum = matrix1 + matrix2
matrix_sum

array([[ 9, 18,  8, 17],
       [10, 14, 11,  3],
       [ 8, 16,  2,  5],
       [ 4,  9,  7,  9]])

In [42]:
matrix_diff = matrix1 - matrix2
matrix_diff

array([[ 7, -2,  2,  3],
       [ 0, -6, -5,  1],
       [ 2,  4,  0, -3],
       [-2,  1, -5, -1]])

In [43]:
matrix_product = matrix1 * matrix2
matrix_product

array([[ 8, 80, 15, 70],
       [25, 40, 24,  2],
       [15, 60,  1,  4],
       [ 3, 20,  6, 20]])

In [45]:
matrix_division = np.divide(matrix1, matrix2, where=(matrix2 != 0))
matrix_division

array([[8.        , 0.8       , 1.66666667, 1.42857143],
       [1.        , 0.4       , 0.375     , 2.        ],
       [1.66666667, 1.66666667, 1.        , 0.25      ],
       [0.33333333, 1.25      , 0.16666667, 0.8       ]])

In [46]:
x = np.arange(9.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [47]:
x1 = x.reshape(3, 3)
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [48]:
x2 = np.arange(3.)
x2

array([0., 1., 2.])

In [49]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [50]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [51]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [52]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])